name: Deploy to production server on push to main branch

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: main

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 20.17.0

      - name: Install dependencies
        run: npm ci

      - name: Deploy using ssh
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.DEPLOYMENT_HOST }}
          username: ${{ secrets.DEPLOYMENT_USERNAME }}
          key: ${{ secrets.DEPLOYMENT_PRIVATE_KEY }}
          script: |
            # Navigate to your app directory
            cd /var/www/api.demo.lettutor.com/movie-api

            # Stop the existing PM2 process
            pm2 stop movie-api || true

            # Remove old files of dist
            rm -rf dist

            # Install any new dependencies if package.json has changed
            npm ci

            # Run build
            npm run build

            # Restart the application with PM2
            pm2 start dist/main.js --name "movie-api" --time

            # Save the PM2 process list for restart on reboot
            pm2 save

            # Restart nginx
            sudo systemctl restart nginx
