name: Deploy to production server on push to main branch

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: main

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 20.17.0

      - name: Install dependencies
        run: npm ci

      - name: Build the application
        run: npm run build

      - name: Set up Nginx
        run: |
          sudo apt update
          sudo apt install -y nginx
          echo "server {
              listen 80;
              server_name api.demo.letcode.com;

              location / {
                  proxy_pass http://localhost:3001;
                  proxy_http_version 1.1;
                  proxy_set_header Upgrade \$http_upgrade;
                  proxy_set_header Connection 'upgrade';
                  proxy_set_header Host \$host;
                  proxy_cache_bypass \$http_upgrade;
              }
          }" | sudo tee /etc/nginx/sites-available/api.demo.letcode.com
          sudo ln -s /etc/nginx/sites-available/api.demo.letcode.com /etc/nginx/sites-enabled/
          sudo nginx -t
          sudo systemctl start nginx
          sudo systemctl reload nginx

      - name: Deploy using ssh
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.DEPLOYMENT_HOST }}
          username: ${{ secrets.DEPLOYMENT_USERNAME }}
          key: ${{ secrets.DEPLOYMENT_PRIVATE_KEY }}
          run: |
            sudo systemctl reload nginx
