name: Deploy to production server on push to main branch

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: main

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 20.17.0

      - name: Install dependencies
        run: npm ci

      - name: Create SSH key
        run: |
          mkdir -p ~/.ssh/
          echo "$DEPLOY_KEY" > ~/.ssh/github_do.key
          sudo chmod 600 ~/.ssh/github_do.key
          ssh-keyscan -H $DEPLOY_SERVER > ~/.ssh/known_hosts
        env:
          DEPLOY_KEY: ${{ secrets.DEPLOYMENT_PRIVATE_KEY }}
          DEPLOY_SERVER: ${{ secrets.DEPLOYMENT_HOST }}

      - name: Deploy using ssh
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.DEPLOYMENT_HOST }}
          username: ${{ secrets.DEPLOYMENT_USERNAME }}
          key: ${{ secrets.DEPLOYMENT_PRIVATE_KEY }}
