name: Deploy to production server on push to main branch

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: main

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18.20.4

      - name: Install dependencies
        run: npm ci

      - name: Build the application
        run: npm run build

      - name: Pull latest changes on VPS
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.DEPLOYMENT_HOST }}
          username: ${{ secrets.DEPLOYMENT_USERNAME }}
          key: ${{ secrets.DEPLOYMENT_PRIVATE_KEY }}
          script: |
            cd /var/www/api.demo.lettutor.com/movie-api
            git pull origin main
            npm ci

      - name: Copy dist folder to VPS
        uses: appleboy/scp-action@v0.1.3
        with:
          source: "./dist"
          target: "/var/www/api.demo.lettutor.com/movie-api"
          host: ${{ secrets.DEPLOYMENT_HOST }}
          username: ${{ secrets.DEPLOYMENT_USERNAME }}
          key: ${{ secrets.DEPLOYMENT_PRIVATE_KEY }}

      - name: Restart application with PM2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.DEPLOYMENT_HOST }}
          username: ${{ secrets.DEPLOYMENT_USERNAME }}
          key: ${{ secrets.DEPLOYMENT_PRIVATE_KEY }}
          script: |
            cd /var/www/api.demo.lettutor.com/movie-api
            pm2 restart movie-api || pm2 start dist/main.js --name "movie-api"
